services:
  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: goprojectskeleton
      POSTGRES_PASSWORD: goprojectskeleton
      POSTGRES_DB: goprojectskeleton
    networks:
      - goprojectskeleton-tests
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=65536k
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goprojectskeleton"]
      interval: 1s
      retries: 5
  goprojectskeleton-integration-tests:
    build:
      context: ..
      dockerfile: docker/dockerfile.integration
    env_file:
      - ../test.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../test.env:/app/.env:ro
      - ../src:/app/src
      - ../tests:/app/tests
    networks:
      - goprojectskeleton-tests
    command: ["go", "test", "./tests/integration/...", "-v", "-count=1", "-cover"]

  mailhog:
    image: axllent/mailpit:latest
    # platform: linux/amd64
    restart: always
    networks:
      - goprojectskeleton-tests

networks:
  goprojectskeleton-tests:
    external: false
